import { Libre_Franklin, Merriweather_Sans, Radio_Canada, Rethink_Sans } from "next/font/google";
import "./globals.css";
import { clarity } from '@microsoft/clarity';
import GoogleAnalytics from "@/lib/integrations/googleAnalytics";

// const libreFranklin = Libre_Franklin({
//   variable: "--font-libre-franklin",
//   subsets: ["latin"],
// });

// const rethinkSans = Rethink_Sans({
//   variable: "--font-rethink-sans",
//   subsets: ["latin"],
// });

const merriweatherSans = Merriweather_Sans({
  variable: "--font-merriweather-sans",
  subsets: ["latin"],
  weight: ["300", "400", "700", "800"],
});

const radioCanada = Radio_Canada({
  variable: "--font-radio-canada",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  clarity.init("v8nubzutzz")
  return (
    <html lang="en">
      <head>
        <GoogleAnalytics />
      </head>
      <body
        className={`${merriweatherSans.variable} ${radioCanada.variable} antialiased font-default`}
      >
        {children}
      </body>
    </html>
  );
}
